<?php

namespace common\models\control;

use common\models\ProgramType;
use Yii;

/**
 * This is the model class for table "control_primary_product".
 *
 * @property int $id
 * @property int $control_primary_data_id
 * @property string|null $product_type
 * @property string|null $nd
 * @property string|null $nd_type
 * @property string|null $number_blank
 * @property string|null $number_reestr
 * @property int|null $date_from
 * @property int|null $date_to
 *
 * @property PrimaryData $controlPrimaryData
 */
class PrimaryProduct extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'control_primary_product';
    }

    public function rules()
    {
        return [
            [['control_primary_data_id'], 'required'],
            [['control_primary_data_id', 'product_type_id'], 'integer'],
            [['nd', 'nd_type'], 'safe'],
            [['number_blank', 'number_reestr', 'date_from', 'date_to', 'product_name'], 'string', 'max' => 255],
            [['control_primary_data_id'], 'exist', 'skipOnError' => true, 'targetClass' => PrimaryData::className(), 'targetAttribute' => ['control_primary_data_id' => 'id']],
            [['product_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => ProductType::className(), 'targetAttribute' => ['product_type_id' => 'id']],
        ];
    }

    public function beforeSave($insert)
    {
        if (!parent::beforeSave($insert)) {
            return false;
        }

        $this->date_from = strtotime($this->date_from);
        $this->date_to = strtotime($this->date_to);

        return true;
    }

    public function afterFind()
    {
        $this->date_from = $this->date_from ? Yii::$app->formatter->asDate($this->date_from, 'M/dd/yyy') : '';
        $this->date_to = $this->date_to ? Yii::$app->formatter->asDate($this->date_to, 'M/dd/yyy') : '';

        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'control_primary_data_id' => 'Control Primary Data ID',
            'product_type_id' => 'Mahsulot turi',
            'product_name' => 'Mahsulot nomi',
            'nd' => 'Mahsulot normativ hujjatlari',
            'nd_type' => 'Normativ hujjat toifalari',
            'number_blank' => 'Blank raqami',
            'number_reestr' => 'Reesstr raqami',
            'date_from' => 'Berilgan sana',
            'date_to' => 'Amal qilish muddati',
        ];
    }

    /**
     * Gets query for [[ControlPrimaryData]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPrimaryData()
    {
        return $this->hasOne(PrimaryData::className(), ['id' => 'control_primary_data_id']);
    }
}
