<?php

namespace common\models\control;

use Yii;

/**
 * This is the model class for table "pro_primary_data".
 *
 * @property int $id
 * @property int $control_primary_id
 * @property string $product_name
 * @property int $product_date
 *
 * @property PrimaryProduct $controlPrimary
 */
class ProPrimaryData extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'pro_primary_data';
    }

    public function rules()
    {
        return [
            [['control_primary_id'], 'integer'],
            [['product_date'], 'string'],
            [['product_name'], 'string', 'max' => 255],
            [['control_primary_id'], 'exist', 'skipOnError' => true, 'targetClass' => PrimaryProduct::className(), 'targetAttribute' => ['control_primary_id' => 'id']],
        ];
    }

    public function beforeSave($insert)
    {
        if (!parent::beforeSave($insert)) {
            return false;
        }

        $this->product_date = strtotime($this->product_date);

        return true;
    }

    public function afterFind()
    {
        $this->product_date = Yii::$app->formatter->asDate($this->product_date, 'M/dd/yyyy');
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'control_primary_id' => 'Control Primary ID',
            'product_name' => 'nomi',
            'product_date' => 'sanasi',
        ];
    }

    public function getControlPrimary()
    {
        return $this->hasOne(PrimaryProduct::className(), ['id' => 'control_primary_id']);
    }
}
